"""SQLAlchemy 2.0 ORM models — tenants, conversations, documents."""

from __future__ import annotations

import secrets
import uuid
from datetime import datetime, timezone
from typing import Any

from sqlalchemy import JSON, DateTime, Index, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from app.db.database import Base


def _utcnow() -> datetime:
    """Return the current UTC time (timezone-aware)."""
    return datetime.now(timezone.utc)


def _new_uuid() -> str:
    return str(uuid.uuid4())


def _new_api_key() -> str:
    """Generate a URL-safe random API key: `sk-<32 random bytes>`."""
    return f"sk-{secrets.token_urlsafe(32)}"


# ─────────────────────────────────────────────────────────────────────────────
#  Tenant
# ─────────────────────────────────────────────────────────────────────────────

class Tenant(Base):
    """
    Represents a business client (tenant).

    Each tenant has:
    - An isolated Qdrant namespace (filtered by tenant_id payload).
    - Their own document store under data/tenants/{id}/documents/.
    - A unique API key used in the X-Tenant-ID / X-API-Key header.
    - A JSON config blob for per-tenant settings.
    """

    __tablename__ = "tenants"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid
    )
    name: Mapped[str] = mapped_column(String(255), nullable=False)
    api_key: Mapped[str] = mapped_column(
        String(64),
        unique=True,
        nullable=False,
        default=_new_api_key,
        index=True,
        comment="Bearer token used to authenticate API calls",
    )
    plan_tier: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="free",
        comment="free | standard | pro",
    )
    # Flexible per-tenant configuration
    config: Mapped[dict[str, Any]] = mapped_column(
        JSON,
        nullable=False,
        default=dict,
        comment="Per-tenant config: tools, limits, custom prompts, etc.",
    )
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
    )

    __table_args__ = (
        Index("ix_tenants_api_key", "api_key"),
        Index("ix_tenants_is_active", "is_active"),
    )


# ─────────────────────────────────────────────────────────────────────────────
#  Conversation
# ─────────────────────────────────────────────────────────────────────────────

class Conversation(Base):
    """
    Persists conversation turns per tenant + session.

    session_id — Unique session identifier for memory continuity.
    messages   — JSON list of {role, content, timestamp, metadata?} dicts.
                 Short-term context is served from TTLCache; this table
                 is the durable long-term archive.
    """

    __tablename__ = "conversations"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid
    )
    tenant_id: Mapped[str] = mapped_column(
        String(36), nullable=False, index=True
    )
    session_id: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        index=True,
        comment="Arbitrary session UUID generated by web client",
    )
    messages: Mapped[list[dict[str, Any]]] = mapped_column(
        JSON, nullable=False, default=list
    )
    # Metadata about the session (device, channel, etc.)
    session_meta: Mapped[dict[str, Any]] = mapped_column(
        JSON, nullable=False, default=dict
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
    )

    __table_args__ = (
        Index("ix_conversations_tenant_session", "tenant_id", "session_id"),
    )


# ─────────────────────────────────────────────────────────────────────────────
#  Document
# ─────────────────────────────────────────────────────────────────────────────

class Document(Base):
    """
    Tracks every document ingested into the knowledge base.

    Lifecycle: pending → processing → completed | failed

    file_path is relative to the app's data directory so the DB
    is portable across machines.
    """

    __tablename__ = "documents"

    id: Mapped[str] = mapped_column(
        String(36), primary_key=True, default=_new_uuid
    )
    tenant_id: Mapped[str] = mapped_column(
        String(36), nullable=False, index=True
    )
    filename: Mapped[str] = mapped_column(String(512), nullable=False)
    # Path relative to settings.data_dir  e.g. "tenants/abc/documents/foo.pdf"
    file_path: Mapped[str] = mapped_column(Text, nullable=False)
    doc_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="pdf | docx | xlsx | html | image | audio | text | web",
    )
    status: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        default="pending",
        index=True,
        comment="pending | processing | completed | failed",
    )
    # Number of chunks indexed into Qdrant (set on completion)
    chunk_count: Mapped[int | None] = mapped_column(nullable=True, default=None)
    # Arbitrary doc_metadata: source URL, page count, error message, etc.
    # Python attribute is doc_metadata; DB column name stays "metadata"
    # (SQLAlchemy reserves "metadata" as a class attribute on the Declarative Base)
    doc_metadata: Mapped[dict[str, Any]] = mapped_column(
        JSON, nullable=False, default=dict, name="metadata"
    )
    error_message: Mapped[str | None] = mapped_column(Text, nullable=True, default=None)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        default=_utcnow,
        onupdate=_utcnow,
    )

    __table_args__ = (
        Index("ix_documents_tenant_status", "tenant_id", "status"),
    )
